# xml/Makefile

OBJS := \
	CInstancingOperator.o \
	COperatorGenerator.o \

TARGETS := $(OBJS)

include ../Makefile.in

CInstancingOperator.o: CInstancingOperator.cpp CInstancingOperator.hpp
COperatorGenerator.o: COperatorGenerator.cpp COperatorGenerator.hpp
